name: simple_widget_snapshot
description: Simple library for widget snapshot, easy to use for send image from specific widget.
version: 2.0.1
repository: https://github.com/JhonaCodes/simple_widget_snapshot
homepage: https://github.com/JhonaCodes/simple_widget_snapshot

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0