name: simple_widget_snapshot
description: Simple library for widget snapshot, easy to use for send image from specific widget.
version: 2.0.0
repository: https://github.com/JhonaCodes/simple_widget_snapshot
homepage: https://github.com/JhonaCodes/simple_widget_snapshot

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0